version: 0.0.14.{build}
shallow_clone: true

build_script:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall" x86'
  - nmake -f Makefile.nmake
  
  - SET zip=ssocks-win32-%APPVEYOR_BUILD_VERSION%.zip
  - 7z a %zip% ./bin/*.exe ./src/*.conf ./src/*.auth
  - appveyor PushArtifact %zip%
